export const ASSET_PREFIX = "/AKRI-BAKES";

const cakeImages = {
  // Celebration Cakes — Naga celebration themed
  "Black Forest": `${ASSET_PREFIX}/products/celebration-01.jpg`,
  "White Forest": `${ASSET_PREFIX}/products/celebration-02.jpg`,
  Blueberry: `${ASSET_PREFIX}/products/celebration-03.jpg`,
  "Red Velvet with Cream Cheese": `${ASSET_PREFIX}/products/celebration-04.jpg`,
  "Blue Velvet with Cream Cheese": `${ASSET_PREFIX}/products/celebration-05.jpg`,
  "Tres Leches (Milk Cake) — Plain": `${ASSET_PREFIX}/products/celebration-06.jpg`,
  "Rasmalai, Nuts & Rasgula": `${ASSET_PREFIX}/products/celebration-07.jpg`,
  "Chocolate & Nuts": `${ASSET_PREFIX}/products/celebration-08.jpg`,
  "Carrot Cake with Cream Cheese": `${ASSET_PREFIX}/products/celebration-09.jpg`,
  "Dark Chocolate Truffle": `${ASSET_PREFIX}/products/celebration-10.jpg`,
  "Tiramisu with Mascarpone": `${ASSET_PREFIX}/products/celebration-11.jpg`,
  "Matcha Strawberry White Chocolate": `${ASSET_PREFIX}/products/celebration-12.jpg`,
  "Lemon Meringue Cake": `${ASSET_PREFIX}/products/celebration-13.jpg`,
  "Russian Honey Cake": `${ASSET_PREFIX}/products/celebration-14.jpg`,
  "Fruit Gateaux": `${ASSET_PREFIX}/products/celebration-15.jpg`,
  "Coconut-Lotus Biscoff / Raspberry Cake": `${ASSET_PREFIX}/products/celebration-16.jpg`,
  "Chocolate World Cake": `${ASSET_PREFIX}/products/celebration-17.jpg`,
  "White Chocolate Truffle": `${ASSET_PREFIX}/products/celebration-18.jpg`,
  "Rainbow Cake": `${ASSET_PREFIX}/products/celebration-19.jpg`,
  "Salted Nutty Caramel Fudge": `${ASSET_PREFIX}/products/celebration-20.jpg`,

  // Other real customer photos
  "Butterscotch Delight": `${ASSET_PREFIX}/products/cake-03.jpg`,
  Butterscotch: `${ASSET_PREFIX}/products/cake-03.jpg`,
  "Lotus Biscoff Cheesecake": `${ASSET_PREFIX}/products/cake-04.jpg`,
  Tiramisu: `${ASSET_PREFIX}/products/cake-05.jpg`,
  "Blueberry Cheesecake": `${ASSET_PREFIX}/products/cake-07.jpg`,
  "Lemon Meringue Tart": `${ASSET_PREFIX}/products/cake-09.jpg`,
  "New York Cheesecake": `${ASSET_PREFIX}/products/cake-10.jpg`,
  "Peach Cheesecake": `${ASSET_PREFIX}/products/cake-11.jpg`,
  "Oreo Chocolate": `${ASSET_PREFIX}/products/cake-12.jpg`,
  "Strawberry Cheesecake": `${ASSET_PREFIX}/products/cake-13.jpg`,
  "Lemon Meringue Cheesecake": `${ASSET_PREFIX}/products/cake-14.jpg`,
  "Mango Coconut Sticky Rice Cheesecake": `${ASSET_PREFIX}/products/cake-19.jpg`,

  // Stock photos
  "Japanese Cheesecake": `${ASSET_PREFIX}/products/stock-09.jpg`,
  "Chocolate Cheesecake": `${ASSET_PREFIX}/products/stock-08.jpg`,
  "Raspberry Cheesecake": `${ASSET_PREFIX}/products/stock-10.jpg`,
  "Baklava Pista Cheesecake": `${ASSET_PREFIX}/products/stock-11.jpg`,
  "Mix Berries Yogurt Crust Cheesecake": `${ASSET_PREFIX}/products/stock-12.jpg`,
  "Basque Burnt Cheesecake": `${ASSET_PREFIX}/products/stock-13.jpg`,
  "Red Velvet Cheesecake": `${ASSET_PREFIX}/products/stock-14.jpg`,
  "Coconut White Chocolate Cheesecake": `${ASSET_PREFIX}/products/stock-15.jpg`,
  "Mango Mousse": `${ASSET_PREFIX}/products/stock-16.jpg`,
  "Young Coconut Mousse": `${ASSET_PREFIX}/products/stock-17.jpg`,
  "Hazelnut Pralin Mousse": `${ASSET_PREFIX}/products/stock-18.jpg`,
  "Mandarine Orange Cheese Mousse": `${ASSET_PREFIX}/products/stock-19.jpg`,
  "Raspberry White Mousse": `${ASSET_PREFIX}/products/stock-20.jpg`,
  "Banoffee Mousse": `${ASSET_PREFIX}/products/stock-21.jpg`,
  "Chocolate Kunaffa Pistachio Mousse": `${ASSET_PREFIX}/products/stock-22.jpg`,

  // Stock photos — plain & cream cakes
  "Almond Cake": `${ASSET_PREFIX}/products/stock-23.jpg`,
  "Banana Cashew": `${ASSET_PREFIX}/products/stock-24.jpg`,
  "Banoffee Pie": `${ASSET_PREFIX}/products/stock-25.jpg`,
  "Butter Cake": `${ASSET_PREFIX}/products/stock-26.jpg`,
  "Butter Vanilla": `${ASSET_PREFIX}/products/stock-27.jpg`,
  Carrot: `${ASSET_PREFIX}/products/stock-28.jpg`,
  "Carrot Cake Cream Cheese": `${ASSET_PREFIX}/products/stock-29.jpg`,
  "Carrot Raisin Butter Cake": `${ASSET_PREFIX}/products/stock-30.jpg`,
  Chocolate: `${ASSET_PREFIX}/products/stock-31.jpg`,
  "Chocolate Fudge": `${ASSET_PREFIX}/products/stock-32.jpg`,
  "Chocolate Tart": `${ASSET_PREFIX}/products/stock-33.jpg`,
  "Chocolate Walnut & Caramel": `${ASSET_PREFIX}/products/stock-34.jpg`,
  "Chocolate Walnut Cake": `${ASSET_PREFIX}/products/stock-35.jpg`,
  "Classic Coffee": `${ASSET_PREFIX}/products/stock-36.jpg`,
  "Classic Vanilla Butter": `${ASSET_PREFIX}/products/stock-37.jpg`,
  "Coconut Biscoff": `${ASSET_PREFIX}/products/stock-38.jpg`,
  "Coconut Pista": `${ASSET_PREFIX}/products/stock-39.jpg`,
  Coffee: `${ASSET_PREFIX}/products/stock-40.jpg`,
  "Coffee Nutty Praline": `${ASSET_PREFIX}/products/stock-41.jpg`,
  "Combo Flavour": `${ASSET_PREFIX}/products/stock-42.jpg`,
  "Dark Forest": `${ASSET_PREFIX}/products/stock-43.jpg`,
  "Divine Mango Cream": `${ASSET_PREFIX}/products/stock-44.jpg`,
  "Dry Fruits Cake": `${ASSET_PREFIX}/products/stock-45.jpg`,
  "Earl Grey": `${ASSET_PREFIX}/products/stock-46.jpg`,
  "Exotic Pineapple": `${ASSET_PREFIX}/products/stock-47.jpg`,
  "Fresh Fruit Gateaux": `${ASSET_PREFIX}/products/stock-48.jpg`,
  "Fruit & Nuts": `${ASSET_PREFIX}/products/stock-49.jpg`,
  "Key Lime Pie": `${ASSET_PREFIX}/products/stock-50.jpg`,
  Lemon: `${ASSET_PREFIX}/products/stock-51.jpg`,
  "Lemon Cake": `${ASSET_PREFIX}/products/stock-52.jpg`,
  "Lemon Meringue": `${ASSET_PREFIX}/products/stock-53.jpg`,
  "Lemon Vanilla": `${ASSET_PREFIX}/products/stock-54.jpg`,
  Mango: `${ASSET_PREFIX}/products/stock-55.jpg`,
  "Mango Pista": `${ASSET_PREFIX}/products/stock-56.jpg`,
  "Orange Caramel Pudding Cake": `${ASSET_PREFIX}/products/stock-57.jpg`,
  "Orange Raisin": `${ASSET_PREFIX}/products/stock-58.jpg`,
  Pineapple: `${ASSET_PREFIX}/products/stock-59.jpg`,
  "Plum Cake": `${ASSET_PREFIX}/products/stock-60.jpg`,
  "Red Velvet": `${ASSET_PREFIX}/products/stock-61.jpg`,
  "Red Velvet with Cheesecake": `${ASSET_PREFIX}/products/stock-62.jpg`,
  "Regular / Black Sticky Rice Cake": `${ASSET_PREFIX}/products/stock-63.jpg`,
  "Russian Honey": `${ASSET_PREFIX}/products/stock-64.jpg`,
  "Salted Caramel Hazelnut": `${ASSET_PREFIX}/products/stock-65.jpg`,
  Strawberry: `${ASSET_PREFIX}/products/stock-66.jpg`,
  "Strawberry Burst": `${ASSET_PREFIX}/products/stock-67.jpg`,
  "Triple Berries": `${ASSET_PREFIX}/products/stock-68.jpg`,
  Vanilla: `${ASSET_PREFIX}/products/stock-69.jpg`,
  "Vanilla Custard": `${ASSET_PREFIX}/products/stock-70.jpg`,
  "Walnut Cake": `${ASSET_PREFIX}/products/stock-71.jpg`,

  // Product page extra names
  "Blueberry Cake": `${ASSET_PREFIX}/products/cake-27.jpg`,
  "Matcha Strawberry": `${ASSET_PREFIX}/products/cake-18.jpg`,
  "Coconut Lotus Biscoff": `${ASSET_PREFIX}/products/cake-25.jpg`,
  "Mango Cheesecake": `${ASSET_PREFIX}/products/stock-72.jpg`,
  "Mango Mousse Cake": `${ASSET_PREFIX}/products/stock-16.jpg`,
  "Chocolate Mousse Cake": `${ASSET_PREFIX}/products/stock-73.jpg`,
  "Coffee Mousse Cake": `${ASSET_PREFIX}/products/stock-74.jpg`,
  "Strawberry Mousse": `${ASSET_PREFIX}/products/stock-75.jpg`,
};

export function getCakeImage(name) {
  return cakeImages[name] || null;
}
